

  CREATE TABLE t1(a);
  CREATE TABLE t2(w);
  CREATE TRIGGER temp.r1 AFTER INSERT ON main.t2 BEGIN
    INSERT INTO t1(a) VALUES(new.w);
  END;
  CREATE TEMP TABLE t2(x);



  ALTER TABLE main.t2 RENAME TO t3;



  INSERT INTO t3 VALUES('WWW');
  SELECT * FROM t1;

