
ANALYZE t1a;
EXPLAIN QUERY PLAN SELECT * FROM t1 WHERE a=123;

EXPLAIN QUERY PLAN SELECT * FROM t1 WHERE b=123;

EXPLAIN QUERY PLAN SELECT * FROM t1 WHERE c=2;

EXPLAIN QUERY PLAN SELECT * FROM t1 WHERE a=123 AND b=123
