
ANALYZE t1cd;
EXPLAIN QUERY PLAN SELECT * FROM t1 WHERE a=123;

EXPLAIN QUERY PLAN SELECT * FROM t1 WHERE b=123;

EXPLAIN QUERY PLAN SELECT * FROM t1 WHERE c=?;

EXPLAIN QUERY PLAN SELECT * FROM t1 WHERE c=2;

EXPLAIN QUERY PLAN SELECT * FROM t1 WHERE c=2;

EXPLAIN QUERY PLAN SELECT * FROM t1 WHERE a=123 AND b=123

EXPLAIN QUERY PLAN SELECT * FROM t1 WHERE c=123 AND b=123

EXPLAIN QUERY PLAN SELECT * FROM t1 WHERE a=123 AND c=123

EXPLAIN QUERY PLAN SELECT * FROM t1 WHERE c=123 AND d=123 AND b=123
