PRAGMA auto_vacuum = 0;
    BEGIN;
    CREATE TABLE t1(x,y);
    INSERT INTO t1 VALUES(1,1);
    INSERT OR IGNORE INTO t1 SELECT x*2,y FROM t1;
    INSERT OR IGNORE INTO t1 SELECT x*3,y FROM t1;
    INSERT OR IGNORE INTO t1 SELECT x*5,y FROM t1;
    INSERT OR IGNORE INTO t1 SELECT x*7,y FROM t1;
    INSERT OR IGNORE INTO t1 SELECT x*11,y FROM t1;
    INSERT OR IGNORE INTO t1 SELECT x*13,y FROM t1;
    CREATE INDEX t1i1 ON t1(x);
    CREATE TABLE t2 AS SELECT x,2 as y FROM t1 WHERE rowid%5!=0;
    COMMIT;
  
PRAGMA integrity_check
UPDATE t1 SET y=1
UPDATE t2 SET y='abcdef-uvwxyz'
BEGIN; UPDATE t2 SET y='abcdef-uvwxyz'; ROLLBACK;
PRAGMA integrity_check
BEGIN; UPDATE t2 SET y='abcdef-uvwxyz'; ROLLBACK;
BEGIN; UPDATE t2 SET y='abcdef-uvwxyz'; ROLLBACK;
BEGIN; DELETE FROM t1 WHERE x>13; ROLLBACK;
BEGIN; DELETE FROM t1 WHERE x>13; ROLLBACK;
BEGIN; UPDATE t2 SET y='abcdef-uvwxyz'; ROLLBACK;
BEGIN; CREATE TABLE t3 AS SELECT x,3 as y FROM t2 WHERE rowid%5!=0; ROLLBACK;
SELECT count(*) FROM sqlite_master;
BEGIN; CREATE TABLE t3 AS SELECT x,3 as y FROM t2 WHERE rowid%5!=0; ROLLBACK;
INSERT INTO t1 VALUES (1, $blob) 
DELETE FROM t1 WHERE rowid = (SELECT max(rowid) FROM t1)
SELECT count(*) FROM sqlite_master;
SELECT count(*) FROM sqlite_master
SELECT count(*) FROM t1
SELECT count(*) FROM t1 WHERE x>13
SELECT count(*) FROM t2
SELECT count(*) FROM t2 WHERE x<13
BEGIN; UPDATE t1 SET y=1; ROLLBACK;
BEGIN; UPDATE t2 SET y='abcdef-uvwxyz'; ROLLBACK;
BEGIN; DELETE FROM t1 WHERE x>13; ROLLBACK;
BEGIN; DELETE FROM t2 WHERE x<13; ROLLBACK;
BEGIN; CREATE TABLE t3 AS SELECT x,3 as y FROM t2 WHERE rowid%5!=0; ROLLBACK;
PRAGMA integrity_check
