DELETE FROM test1
DELETE FROM sqlite_master
CREATE TABLE table1(f1 int, f2 int)
INSERT INTO table1 VALUES(1,2)
INSERT INTO table1 VALUES(2,4)
INSERT INTO table1 VALUES(3,8)
INSERT INTO table1 VALUES(4,16)
SELECT * FROM table1 ORDER BY f1
DELETE FROM table1 WHERE f1=3
SELECT * FROM table1 ORDER BY f1
CREATE INDEX index1 ON table1(f1)
PRAGMA count_changes=on
EXPLAIN DELETE FROM table1 WHERE f1=3
DELETE FROM 'table1' WHERE f1=3
SELECT * FROM table1 ORDER BY f1
DELETE FROM table1 WHERE f1=2
SELECT * FROM table1 ORDER BY f1
CREATE TABLE table2(f1 int, f2 int)
DELETE FROM table2 WHERE f3=5
DELETE FROM table2 WHERE xyzzy(f1+4)
DELETE FROM table1
SELECT count(*) FROM table1
BEGIN TRANSACTION
$i*$i
COMMIT
SELECT count(*) FROM table1
DELETE FROM table1
BEGIN TRANSACTION
$i*$i
COMMIT
SELECT count(*) FROM table1
PRAGMA count_changes=off
DELETE FROM table1
SELECT count(*) FROM table1
BEGIN TRANSACTION
$i*$i
COMMIT
SELECT count(*) FROM table1
SELECT count(*) FROM table1
SELECT count(*) FROM table1
SELECT f1 FROM table1 ORDER BY f1
SELECT f1 FROM table1 ORDER BY f1
SELECT f1 FROM table1 ORDER BY f1
BEGIN; DELETE FROM table1
$i*$i
DELETE FROM table2
$i*$i
COMMIT
SELECT count(*) FROM table1
SELECT count(*) FROM table2
SELECT f1 FROM table1 WHERE f1<10 ORDER BY f1
SELECT f1 FROM table2 WHERE f1<10 ORDER BY f1
DELETE FROM table1 WHERE f1>7
SELECT f1 FROM table1 ORDER BY f1
DELETE FROM table2 WHERE f1>7
SELECT f1 FROM table2 ORDER BY f1
DELETE FROM table1
SELECT f1 FROM table1
INSERT INTO table1 VALUES(2,3)
SELECT f1 FROM table1
DELETE FROM table2
SELECT f1 FROM table2
INSERT INTO table2 VALUES(2,3)
SELECT f1 FROM table2
CREATE TABLE t3(a);
    INSERT INTO t3 VALUES(1);
    INSERT INTO t3 SELECT a+1 FROM t3;
    INSERT INTO t3 SELECT a+2 FROM t3;
    SELECT * FROM t3;
  
CREATE TABLE cnt(del);
      INSERT INTO cnt VALUES(0);
      CREATE TRIGGER r1 AFTER DELETE ON t3 FOR EACH ROW BEGIN
        UPDATE cnt SET del=del+1;
      END;
      DELETE FROM t3 WHERE a<2;
      SELECT * FROM t3;
    
SELECT * FROM cnt;
    
DELETE FROM t3;
      SELECT * FROM t3;
    
SELECT * FROM cnt;
    
INSERT INTO t3 VALUES(1);
      INSERT INTO t3 SELECT a+1 FROM t3;
      INSERT INTO t3 SELECT a+2 FROM t3;
      CREATE TABLE t4 AS SELECT * FROM t3;
      PRAGMA count_changes=ON;
      DELETE FROM t3;
      DELETE FROM t4;
    
DELETE FROM t3
PRAGMA count_changes=OFF;
    INSERT INTO t3 VALUES(123);
    SELECT * FROM t3;
  
DELETE FROM t3;
  
SELECT * FROM t3
DELETE FROM t3 WHERE 1;
  
SELECT * FROM t3
DELETE FROM t3 WHERE a<100;
  
SELECT * FROM t3
CREATE TABLE t5(a, b);
    CREATE TABLE t6(c, d);
    INSERT INTO t5 VALUES(1, 2);
    INSERT INTO t5 VALUES(3, 4);
    INSERT INTO t5 VALUES(5, 6);
    INSERT INTO t6 VALUES('a', 'b');
    INSERT INTO t6 VALUES('c', 'd');
    CREATE INDEX i5 ON t5(a);
    CREATE INDEX i6 ON t6(c);
  
INSERT INTO t5 VALUES(1, 2);
    INSERT INTO t5 VALUES(3, 4);
    INSERT INTO t5 VALUES(5, 6);
  
DELETE FROM t5;
    INSERT INTO t5 VALUES(1, 2);
    INSERT INTO t5 VALUES(3, 4);
    INSERT INTO t5 VALUES(5, 6);
  
DELETE FROM t5;
    INSERT INTO t5 VALUES(1, 2);
    INSERT INTO t5 VALUES(3, 4);
    INSERT INTO t5 VALUES(5, 6);
  
CREATE TABLE t1(a INT UNIQUE, b INT);
  INSERT INTO t1(a,b) VALUES('1','2');
  SELECT * FROM t1 WHERE a='1' AND b='2';

DELETE FROM t1 WHERE a='1' AND b='2';

SELECT * FROM t1 WHERE a='1' AND b='2';

CREATE TABLE t11(a INTEGER PRIMARY KEY, b INT);
  WITH RECURSIVE cnt(x) AS (VALUES(1) UNION ALL SELECT x+1 FROM cnt WHERE x<20)
    INSERT INTO t11(a,b) SELECT x, (x*17)%100 FROM cnt;
  SELECT * FROM t11;

DELETE FROM t11 AS xyz
   WHERE EXISTS(SELECT 1 FROM t11 WHERE t11.a>xyz.a AND t11.b<=xyz.b);
  SELECT * FROM t11;

CREATE TABLE t0(vkey INTEGER, pkey INTEGER,c1 INTEGER);
  INSERT INTO t0 VALUES(2,1,-20),(2,2,NULL),(2,3,0),(8,4,95);
  DELETE FROM t0 WHERE NOT (
    (t0.vkey <= t0.c1) AND
    (t0.vkey <> (SELECT vkey FROM t0 ORDER BY vkey LIMIT 1 OFFSET 2))
  );
  SELECT * FROM t0;

