SELECT rowid FROM t1 WHERE content MATCH 'one'
SELECT rowid FROM t1 WHERE content MATCH 'one two'
SELECT rowid FROM t1 WHERE content MATCH 'two one'
SELECT rowid FROM t1 WHERE content MATCH 'one two three'
SELECT rowid FROM t1 WHERE content MATCH 'one three two'
SELECT rowid FROM t1 WHERE content MATCH 'two three one'
SELECT rowid FROM t1 WHERE content MATCH 'two one three'
SELECT rowid FROM t1 WHERE content MATCH 'three one two'
SELECT rowid FROM t1 WHERE content MATCH 'three two one'
SELECT rowid FROM t1 WHERE content MATCH 'one two THREE'
SELECT rowid FROM t1 WHERE content MATCH '  ONE    Two   three  '
SELECT rowid FROM t1 WHERE content MATCH '"one"'
SELECT rowid FROM t1 WHERE content MATCH '"one two"'
SELECT rowid FROM t1 WHERE content MATCH '"two one"'
SELECT rowid FROM t1 WHERE content MATCH '"one two three"'
SELECT rowid FROM t1 WHERE content MATCH '"one three two"'
SELECT rowid FROM t1 WHERE content MATCH '"one two three four"'
SELECT rowid FROM t1 WHERE content MATCH '"one three two four"'
SELECT rowid FROM t1 WHERE content MATCH '"one three five"'
SELECT rowid FROM t1 WHERE content MATCH '"one three" five'
SELECT rowid FROM t1 WHERE content MATCH 'five "one three"'
SELECT rowid FROM t1 WHERE content MATCH 'five "one three" four'
SELECT rowid FROM t1 WHERE content MATCH 'five four "one three"'
SELECT rowid FROM t1 WHERE content MATCH '"one three" four five'
SELECT rowid FROM t1 WHERE content MATCH 'one'
SELECT rowid FROM t1 WHERE content MATCH 'one -two'
SELECT rowid FROM t1 WHERE content MATCH '-two one'
SELECT rowid FROM t1 WHERE content MATCH 'one OR two'
SELECT rowid FROM t1 WHERE content MATCH '"one two" OR three'
SELECT rowid FROM t1 WHERE content MATCH 'three OR "one two"'
SELECT rowid FROM t1 WHERE content MATCH 'one two OR three'
SELECT rowid FROM t1 WHERE content MATCH 'three OR two one'
SELECT rowid FROM t1 WHERE content MATCH 'one two OR three OR four'
SELECT rowid FROM t1 WHERE content MATCH 'two OR three OR four one'
INSERT INTO t1(content) VALUES(NULL)
SELECT content FROM t1 WHERE rowid=$rowid
SELECT rowid FROM t1 WHERE content MATCH NULL
