CREATE VIRTUAL TABLE ft USING fts3(x) 
INSERT INTO ft VALUES(NULL) 
INSERT INTO ft SELECT * FROM ft 
INSERT INTO ft SELECT * FROM ft 
INSERT INTO ft SELECT * FROM ft 
INSERT INTO ft SELECT * FROM ft 
INSERT INTO ft SELECT * FROM ft 
INSERT INTO ft SELECT * FROM ft 
INSERT INTO ft SELECT * FROM ft 
INSERT INTO ft SELECT * FROM ft 
INSERT INTO ft SELECT * FROM ft 
INSERT INTO ft SELECT * FROM ft 
INSERT INTO ft SELECT * FROM ft 
INSERT INTO ft SELECT * FROM ft 
INSERT INTO ft SELECT * FROM ft 
INSERT INTO ft SELECT * FROM ft 
INSERT INTO ft SELECT * FROM ft 
INSERT INTO ft SELECT * FROM ft 
INSERT INTO ft SELECT * FROM ft 
UPDATE ft SET x = 'abc' || rowid 
SELECT count(*) FROM ft WHERE x MATCH 'abc*' 
