
DELETE FROM tbl1
INSERT INTO tbl1 VALUES('$word')
SELECT t1 FROM tbl1 ORDER BY t1

SELECT length(t1) FROM tbl1 ORDER BY t1

SELECT substr(t1,1,2) FROM tbl1 ORDER BY t1

SELECT substr(t1,1,3) FROM tbl1 ORDER BY t1

SELECT substr(t1,2,2) FROM tbl1 ORDER BY t1

SELECT substr(t1,2,3) FROM tbl1 ORDER BY t1

SELECT substr(t1,3,2) FROM tbl1 ORDER BY t1

SELECT substr(t1,4,2) FROM tbl1 ORDER BY t1

SELECT substr(t1,-1,1) FROM tbl1 ORDER BY t1

SELECT substr(t1,-3,2) FROM tbl1 ORDER BY t1

SELECT substr(t1,-4,3) FROM tbl1 ORDER BY t1

DELETE FROM tbl1
INSERT INTO tbl1 VALUES('$word')
SELECT t1 FROM tbl1
