

  DROP TABLE IF EXISTS t1;
  CREATE TABLE t1(x INT PRIMARY KEY, y INT);
  WITH RECURSIVE c(x) AS (VALUES(1) UNION ALL SELECT x+1 FROM c WHERE x<8)
    INSERT INTO t1(x,y) SELECT x, x*100 FROM c;
  DROP TABLE IF EXISTS t2;
  CREATE TABLE t2(a INT);
  INSERT INTO t2 VALUES(2),(4),(6);
  SELECT * FROM t1 WHERE x IN (SELECT a FROM t2);



  SELECT * FROM t1 WHERE x IN ((SELECT a FROM t2));



  SELECT * FROM t1 WHERE x IN (((SELECT a FROM t2)));



  SELECT * FROM t1 WHERE x IN ((((((SELECT a FROM t2))))));

