

    UPDATE t1 SET b=b*2 
    WHERE b IN (SELECT b FROM t1 WHERE a>8)
  
SELECT b FROM t1 ORDER BY b


    DELETE FROM t1 WHERE b IN (SELECT b FROM t1 WHERE a>8)
  
SELECT a FROM t1 ORDER BY a


    DELETE FROM t1 WHERE b NOT IN (SELECT b FROM t1 WHERE a>4)
  
SELECT a FROM t1 ORDER BY a
