

  BEGIN;
    CREATE TABLE t2(x);
    INSERT INTO t2 VALUES(14);
    INSERT INTO t2 VALUES(35);
    INSERT INTO t2 VALUES(15);
    INSERT INTO t2 VALUES(35);
    INSERT INTO t2 VALUES(16);
  COMMIT;



  CREATE UNIQUE INDEX i3 ON t2(x);

