

  CREATE VIEW v2 AS SELECT * FROM t1 INDEXED BY i1 WHERE a > 5;
  EXPLAIN QUERY PLAN SELECT * FROM v2 



  EXPLAIN QUERY PLAN SELECT * FROM v2 WHERE b = 10 


 DROP INDEX i1 
 SELECT * FROM v2 

 CREATE INDEX i1 ON t1(b) 
 SELECT * FROM v2 

 DROP INDEX i1 ; CREATE INDEX i1 ON t1(a) 
 SELECT * FROM v2 
