

  CREATE TABLE t0(a INT); INSERT INTO t0(a) VALUES (1);
  CREATE TABLE t1(b INT); INSERT INTO t1(b) VALUES (2);
  CREATE VIEW v2(c) AS SELECT 3 FROM t1;
  SELECT * FROM t1 JOIN v2 ON 0     FULL OUTER JOIN t0 ON true;



  SELECT * FROM t1 JOIN v2 ON 1=0   FULL OUTER JOIN t0 ON true;



  SELECT * FROM t1 JOIN v2 ON false FULL OUTER JOIN t0 ON true;

