

    CREATE TABLE ab(a,b);
    INSERT INTO "ab" VALUES(1,2);
    INSERT INTO "ab" VALUES(3,NULL);

    CREATE TABLE xy(x,y);
    INSERT INTO "xy" VALUES(2,3);
    INSERT INTO "xy" VALUES(NULL,1);
  
SELECT * FROM xy LEFT JOIN ab ON 0

SELECT * FROM xy LEFT JOIN ab ON 1

SELECT * FROM xy LEFT JOIN ab ON NULL

SELECT * FROM xy LEFT JOIN ab ON 0 WHERE 0

SELECT * FROM xy LEFT JOIN ab ON 1 WHERE 0

SELECT * FROM xy LEFT JOIN ab ON NULL WHERE 0

SELECT * FROM xy LEFT JOIN ab ON 0 WHERE 1

SELECT * FROM xy LEFT JOIN ab ON 1 WHERE 1

SELECT * FROM xy LEFT JOIN ab ON NULL WHERE 1

SELECT * FROM xy LEFT JOIN ab ON 0 WHERE NULL

SELECT * FROM xy LEFT JOIN ab ON 1 WHERE NULL

SELECT * FROM xy LEFT JOIN ab ON NULL WHERE NULL
