

  CREATE TABLE t0(w);
  CREATE TABLE t1(x);
  CREATE TABLE t2(y);
  CREATE TABLE t3(z);
  INSERT INTO t3 VALUES('t3val');



  SELECT * FROM t1 INNER JOIN t2 ON (0) RIGHT OUTER JOIN t3;



  SELECT * FROM t1 INNER JOIN t2 ON (0) FULL OUTER JOIN t3;



  SELECT * FROM t3 LEFT JOIN t2 ON (0);



  SELECT * FROM t0 RIGHT JOIN t1 INNER JOIN t2 ON (0) RIGHT JOIN t3



  SELECT * FROM t0 RIGHT JOIN t1 INNER JOIN t2 ON (0)

