

  CREATE TABLE t1(a INTEGER COLLATE NOCASE);
  CREATE INDEX i1 ON t1(a);
  INSERT INTO t1 VALUES(' 1x');
  INSERT INTO t1 VALUES(' 1-');



  SELECT * FROM t1 WHERE a LIKE ' 1%';



  SELECT * FROM t1 WHERE a LIKE ' 1-';

