SELECT name FROM sqlite_master WHERE type='table' ORDER BY name
SELECT name FROM sqlite_master WHERE type='table' ORDER BY name
CREATE TABLE t1(a int, b int)
SELECT name FROM sqlite_master WHERE type='table' ORDER BY name
SELECT name FROM sqlite_master WHERE type='table' ORDER BY name
  
INSERT INTO t1 VALUES(1,2)
SELECT * FROM t1
SELECT * FROM t1
SELECT * FROM t1
UPDATE t1 SET a=b, b=a
SELECT * FROM t1
SELECT * FROM t1
BEGIN TRANSACTION
UPDATE t1 SET a = 0 WHERE 0
SELECT * FROM t1
SELECT * FROM t1
ROLLBACK
SELECT * FROM t1
CREATE TABLE t2(x int, y int)
INSERT INTO t2 VALUES(8,9)
SELECT * FROM t2
SELECT * FROM t2
SELECT * FROM t1
SELECT * FROM t2
SELECT * FROM t2
BEGIN TRANSACTION
UPDATE t1 SET a = 0 WHERE 0
BEGIN TRANSACTION
UPDATE t1 SET a = 0 WHERE 0
ROLLBACK
SELECT * FROM t2
UPDATE t1 SET a=b, b=a
BEGIN; SELECT rowid FROM sqlite_master LIMIT 1
UPDATE t1 SET a=b, b=a
ROLLBACK
UPDATE t1 SET a=b, b=a
BEGIN; SELECT rowid FROM sqlite_master LIMIT 1
UPDATE t1 SET a=b, b=a
ROLLBACK
SELECT * FROM t1
ROLLBACK
UPDATE t1 SET a = 0 WHERE 0
BEGIN EXCLUSIVE;
UPDATE t1 SET a = 0 WHERE 0
BEGIN EXCLUSIVE;
BEGIN TRANSACTION
BEGIN TRANSACTION
ROLLBACK
UPDATE t1 SET a=0
ROLLBACK
db2 eval $sql

SELECT * FROM t1
  
INSERT INTO t1(a,b) SELECT 3, tx_exec('SELECT y FROM t2 LIMIT 1');
  
CREATE TEMP TABLE t3(x);
      SELECT * FROM t3;
    
INSERT INTO t3 SELECT tx_exec('SELECT y FROM t2 LIMIT 1');
    
SELECT * FROM t3;
    
UPDATE t1 SET a=tx_exec('SELECT x FROM t2');
    
SELECT * FROM t1;
    
UPDATE t3 SET x=tx_exec('SELECT x FROM t2');
    
SELECT * FROM t3;
    
CREATE TABLE t4(a PRIMARY KEY, b);
    INSERT INTO t4 VALUES(1, 'one');
    INSERT INTO t4 VALUES(2, 'two');
    INSERT INTO t4 VALUES(3, 'three');
  
DELETE FROM t4 
SELECT * FROM sqlite_master 
SELECT * FROM t4 
BEGIN;
    INSERT INTO t4 VALUES(1, 'one');
    INSERT INTO t4 VALUES(2, 'two');
    INSERT INTO t4 VALUES(3, 'three');
    COMMIT;
  
SELECT * FROM t4 
SELECT a FROM t4 ORDER BY a 
PRAGMA integrity_check 
PRAGMA lock_status 
PRAGMA journal_mode = truncate;
    BEGIN;
    UPDATE t4 SET a = 10 WHERE 0;
    COMMIT;
  
PRAGMA lock_status 
