INSERT INTO t1 SELECT x+1, y+100 FROM t1;

SELECT CASE WHEN 1 THEN 1 END;

SELECT 3+EXISTS(SELECT * FROM sqlite_master);

SELECT replace('ababa','a','xyzzy');

CREATE TABLE abc(a PRIMARY KEY, b, c);
  
EXPLAIN SELECT * FROM abc AS t2 WHERE rowid=1;
     EXPLAIN QUERY PLAN SELECT * FROM abc AS t2 WHERE rowid=1;
  
CREATE TABLE t1(a PRIMARY KEY, b UNIQUE);
   CREATE TABLE t2(x,y);
   INSERT INTO t1 VALUES(1,2);
   INSERT INTO t2 SELECT * FROM t1;

PRAGMA integrity_check;

