
INSERT INTO t2 VALUES((SELECT max(a) FROM t2)+1,999)
SELECT max(a) FROM t2
INSERT INTO t2 VALUES(max_a_t2()+1,999)
SELECT max(a) FROM t2


INSERT INTO t2 VALUES((SELECT max(a) FROM t2)+1,999)
SELECT max(a) FROM t2
INSERT INTO t2 VALUES(max_a_t2()+1,999)
 SELECT b FROM t2 WHERE a=(SELECT max(a) FROM t2) 
 SELECT b FROM t2 WHERE a=max_a_t2() 

