

  CREATE TABLE t3(a);
  INSERT INTO t3 VALUES(1),(1);
  CREATE INDEX t3a ON t3(a);
  CREATE TABLE t4(x);
  INSERT INTO t4 VALUES(3),(4);
  CREATE INDEX t4x ON t4(x);
  SELECT a, x FROM t3, t4 ORDER BY 1, 2;



  SELECT a, x FROM t3 CROSS JOIN t4 ORDER BY 1, 2;



  SELECT a, x FROM t4 CROSS JOIN t3 ORDER BY 1, 2;

