

    CREATE TABLE t7(x INTEGER PRIMARY KEY, y);
    CREATE TABLE t7temp(a INTEGER PRIMARY KEY);
    INSERT INTO t7 VALUES(9223372036854775807,'a');
    SELECT y FROM t7;
  


    INSERT INTO t7 VALUES(NULL,'b');
    SELECT x, y FROM t7 ORDER BY x;
  
INSERT INTO t7 VALUES(2,'y');

DELETE FROM t7temp; INSERT INTO t7temp VALUES(1);

      INSERT INTO t7 VALUES(NULL,'x');
      SELECT count(*) FROM t7 WHERE y=='x';
    

DELETE FROM t7temp; INSERT INTO t7temp VALUES(1);

    INSERT INTO t7 VALUES(NULL,'x');
  
INSERT INTO t13(rowid,x) VALUES($n,$n*$n)
