

  CREATE TABLE t1(a, b, c);
  INSERT INTO t1 VALUES(0, 0, 0);
  INSERT INTO t1 VALUES(0, 1, 1);
  INSERT INTO t1 VALUES(1, 0, 2);
  INSERT INTO t1 VALUES(1, 1, 3);

  CREATE INDEX i1 ON t1(a, b);


 SELECT c FROM t1 WHERE (a, b) >= (1, 0) 
2 3

 SELECT c FROM t1 WHERE (a, b) > (1, 0)  
3
