

    SELECT a,b,c FROM 
      (SELECT x AS 'a', y AS 'b', x+y AS 'c' FROM t1 WHERE y=4)
    WHERE a<10 ORDER BY a;
  


    SELECT y FROM (SELECT DISTINCT y FROM t1) WHERE y<5 ORDER BY y
  


    SELECT DISTINCT y FROM (SELECT y FROM t1) WHERE y<5 ORDER BY y
  


    SELECT avg(y) FROM (SELECT DISTINCT y FROM t1) WHERE y<5 ORDER BY y
  


    SELECT avg(y) FROM (SELECT DISTINCT y FROM t1 WHERE y<5) ORDER BY y
  
