

    CREATE TABLE t3(x,y);
    INSERT INTO t3 VALUES(1,NULL);
    INSERT INTO t3 VALUES(2,NULL);
    INSERT INTO t3 VALUES(3,4);
    SELECT count(x), y FROM t3 GROUP BY y ORDER BY 1
  


    CREATE TABLE t4(x,y,z);
    INSERT INTO t4 VALUES(1,2,NULL);
    INSERT INTO t4 VALUES(2,3,NULL);
    INSERT INTO t4 VALUES(3,NULL,5);
    INSERT INTO t4 VALUES(4,NULL,6);
    INSERT INTO t4 VALUES(4,NULL,6);
    INSERT INTO t4 VALUES(5,NULL,NULL);
    INSERT INTO t4 VALUES(5,NULL,NULL);
    INSERT INTO t4 VALUES(6,7,8);
    SELECT max(x), count(x), y, z FROM t4 GROUP BY y, z ORDER BY 1
  
