

    CREATE TABLE t4(
      a INTEGER,
      b VARCHAR(30)
    );
    INSERT INTO t4 VALUES(1,1);
    INSERT INTO t4 VALUES(2,2);
    INSERT INTO t4 VALUES(11,11);
    INSERT INTO t4 VALUES(12,12);
    SELECT a FROM t4 ORDER BY 1;
  


    SELECT b FROM t4 ORDER BY 1
  


    CREATE VIEW v4 AS SELECT * FROM t4;
    SELECT a FROM v4 ORDER BY 1;
  


    SELECT b FROM v4 ORDER BY 1;
  


    SELECT a FROM t4 UNION SELECT a FROM v4 ORDER BY 1;
  


    SELECT b FROM t4 UNION SELECT a FROM v4 ORDER BY 1;
  


    SELECT a FROM t4 UNION SELECT b FROM v4 ORDER BY 1;
  


    SELECT b FROM t4 UNION SELECT b FROM v4 ORDER BY 1;
  

#    SELECT b FROM t4 UNION SELECT b FROM v4 ORDER BY 1 COLLATE numeric;
#  

#    SELECT b FROM t4 UNION SELECT b FROM v4 ORDER BY 1 COLLATE integer;
#  

#    SELECT b FROM t4 UNION SELECT b FROM v4 ORDER BY 1 COLLATE text;
#  

#    SELECT b FROM t4 UNION SELECT b FROM v4 ORDER BY 1 COLLATE blob;
#  

#    SELECT b FROM t4 UNION SELECT b FROM v4 ORDER BY 1 COLLATE clob;
#  

#    SELECT b FROM t4 UNION SELECT b FROM v4 ORDER BY 1 COLLATE varchar;
#  
