

    CREATE TABLE t7(c INTEGER PRIMARY KEY);
    INSERT INTO t7 VALUES(1);
    INSERT INTO t7 VALUES(2);
    INSERT INTO t7 VALUES(3);
    INSERT INTO t7 VALUES(4);
  


    SELECT c FROM t7 WHERE c<=3 ORDER BY c DESC;
  


    SELECT c FROM t7 WHERE c<3 ORDER BY c DESC;
  
