

  CREATE TABLE t1(a) STRICT;



  CREATE TABLE t1(a PRIMARY KEY) STRICT, WITHOUT ROWID;



  CREATE TABLE t1(a PRIMARY KEY) WITHOUT ROWID, STRICT;



  CREATE TABLE t1(a BANJO PRIMARY KEY) WITHOUT ROWID, STRICT;



  CREATE TABLE t1(a TEXT PRIMARY KEY, b INT, c INTEGER, d REAL, e BLOB, f DATE) strict;



  CREATE TABLE t1(a TEXT PRIMARY KEY, b INT, c INTEGER, d REAL, e BLOB, f TEXT(50)) WITHOUT ROWID, STRICT;

