

    SELECT (SELECT a FROM t1);
  


    DELETE FROM t1;
    SELECT (SELECT a FROM t1);
  


    CREATE TABLE t3(a PRIMARY KEY);
    INSERT INTO t3 VALUES(10);
  
INSERT INTO t3 VALUES((SELECT max(a) FROM t3)+1)

INSERT INTO t3 VALUES((SELECT max(a) FROM t3)+1)
