

    CREATE TABLE t3(x int);
    INSERT INTO t3 SELECT a FROM t1 UNION ALL SELECT b FROM t1;
    SELECT * FROM t3 ORDER BY x;
  


    CREATE TABLE t3(x int);
    INSERT INTO t3 SELECT a FROM t1; 
    INSERT INTO t3 SELECT b FROM t1;
    SELECT * FROM t3 ORDER BY x;
  


    SELECT sum(x) FROM (SELECT x FROM t3 ORDER BY x LIMIT 2);
  


    SELECT sum(x) FROM (SELECT x FROM t3 ORDER BY x DESC LIMIT 2);
  


    SELECT (SELECT x FROM t3 ORDER BY x);
  


    SELECT (SELECT x FROM t3 ORDER BY x DESC);
  


    SELECT (SELECT x FROM t3 ORDER BY x LIMIT 1);
  


    SELECT (SELECT x FROM t3 ORDER BY x DESC LIMIT 1);
  


    SELECT (SELECT x FROM t3 ORDER BY x LIMIT 1 OFFSET 2);
  


    SELECT (SELECT x FROM t3 ORDER BY x DESC LIMIT 1 OFFSET 2);
  


    SELECT x FROM t3 WHERE x IN
       (SELECT x FROM t3 ORDER BY x DESC LIMIT 1 OFFSET 2);
  
