

    CREATE TABLE t1(a, b);
    CREATE TEMP TABLE tt1(a, b);
    CREATE TEMP TRIGGER tr1 AFTER INSERT ON t1 BEGIN
      INSERT INTO tt1 VALUES(new.a, new.b);
    END;
  

 INSERT INTO t1 VALUES(1, 2) 
 SELECT * FROM t1 

 SELECT * FROM tt1 

 INSERT INTO t1 VALUES(3, 4) 
 SELECT * FROM t1 

 SELECT * FROM tt1 

 BEGIN; CREATE TABLE t3(a, b); ROLLBACK; 

 INSERT INTO t1 VALUES(5, 6) 
 SELECT * FROM tt1 

 DROP TRIGGER tr1 
