

CREATE TABLE t1(a,b,c);
INSERT INTO t1 VALUES(1,2,3);
SELECT * FROM t1

SELECT * FROM sqlite_master
SELECT * FROM t1

SELECT name FROM sqlite_master

SELECT name FROM sqlite_master


    CREATE TEMP TABLE t2(x,y,z);
    INSERT INTO t2 VALUES(4,5,6);
  
SELECT * FROM t2

SELECT * FROM sqlite_master
SELECT * FROM t2

INSERT INTO t2 VALUES(8,9,0);

INSERT INTO t2 VALUES(8,9,0);
SELECT * FROM t2 ORDER BY x

DELETE FROM t2 WHERE x==8
SELECT * FROM t2 ORDER BY x

DELETE FROM t2
SELECT * FROM t2


     INSERT INTO t2 VALUES(7,6,5);
     INSERT INTO t2 VALUES(4,3,2);
     SELECT * FROM t2 ORDER BY x;
  

DROP TABLE t2;
SELECT * FROM t2
