
 PRAGMA foreign_keys = ON 


  CREATE TABLE pp(x PRIMARY KEY);
  CREATE TABLE cc(y REFERENCES pp DEFERRABLE INITIALLY DEFERRED);
  INSERT INTO pp VALUES('abc');
  INSERT INTO cc VALUES('abc');



  BEGIN;
    DROP TABLE pp;
    DROP TABLE cc;
  COMMIT;



  CREATE TABLE pp(x PRIMARY KEY);
  CREATE TABLE cc(y REFERENCES pp DEFERRABLE INITIALLY DEFERRED);
  INSERT INTO pp VALUES('abc');
  INSERT INTO cc VALUES('abc');



  BEGIN;
    DROP TABLE cc;
    DROP TABLE pp;
  COMMIT;

