

  CREATE TABLE pp1(x PRIMARY KEY);
  CREATE TABLE cc1(y REFERENCES pp1 DEFERRABLE INITIALLY DEFERRED);

  CREATE TABLE pp2(x PRIMARY KEY);
  CREATE TABLE cc2(y REFERENCES pp1 DEFERRABLE INITIALLY DEFERRED);

  INSERT INTO pp1 VALUES(2200);
  INSERT INTO cc1 VALUES(NULL);

  INSERT INTO pp2 VALUES(2200);
  INSERT INTO cc2 VALUES(2200);



  BEGIN;
    DELETE FROM pp2;
    DROP TABLE pp1;
    DROP TABLE cc1;
  COMMIT;



    DROP TABLE cc2;
  COMMIT;

