

  CREATE TABLE pp(x PRIMARY KEY);
  CREATE TABLE cc(
    y INTEGER PRIMARY KEY REFERENCES pp DEFERRABLE INITIALLY DEFERRED
  );
  INSERT INTO pp VALUES(5);
  INSERT INTO cc VALUES(5);



  BEGIN;
    DROP TABLE pp;
    DROP TABLE cc;
  COMMIT;



  CREATE TABLE pp(x PRIMARY KEY);
  CREATE TABLE cc(
    y INTEGER PRIMARY KEY REFERENCES pp DEFERRABLE INITIALLY DEFERRED
  );
  INSERT INTO pp VALUES(5);
  INSERT INTO cc VALUES(5);



  BEGIN;
    DROP TABLE cc;
    DROP TABLE pp;
  COMMIT;

