BEGIN;
    SELECT * FROM abc;
  
BEGIN EXCLUSIVE 
SELECT * FROM abc 
INSERT INTO abc VALUES(1, 2, 3) 
COMMIT 
BEGIN EXCLUSIVE 
BEGIN EXCLUSIVE 
BEGIN IMMEDIATE 
BEGIN 
SELECT * FROM abc 
COMMIT 
SELECT * FROM abc 
CREATE TABLE def(d, e, f) 
ATTACH 'test2.db' AS aux 
BEGIN IMMEDIATE
BEGIN EXCLUSIVE
SELECT * FROM abc
