

    CREATE TABLE t1(a,b);
    INSERT INTO t1 VALUES(1,NULL);
    INSERT INTO t1 VALUES(9,NULL);
    INSERT INTO t1 VALUES(5,NULL);
    INSERT INTO t1 VALUES(123,NULL);
    INSERT INTO t1 VALUES(-10,NULL);
    CREATE UNIQUE INDEX t1b ON t1(b);
  

    SELECT a FROM t1 WHERE b IS NULL ORDER BY a;
  


    SELECT a FROM t1 WHERE b IS NULL ORDER BY b, a;
  
