

    CREATE TABLE t2(a COLLATE NOCASE, b COLLATE BINARY);
    INSERT INTO t2 VALUES('aBc', 'DeF');
  

 SELECT a='abc' FROM t2 GROUP BY a 

 SELECT a='abc' FROM t2 

 SELECT a>b FROM t2 GROUP BY a, b

 SELECT a>b COLLATE BINARY FROM t2 GROUP BY a, b

 SELECT b>a FROM t2 GROUP BY a, b

 SELECT b>a COLLATE NOCASE FROM t2 GROUP BY a, b
