

    CREATE TABLE t2(a,b,c);
    INSERT INTO t2 VALUES(1,1,NULL);
    INSERT INTO t2 VALUES(9,2,NULL);
    INSERT INTO t2 VALUES(5,2,NULL);
    INSERT INTO t2 VALUES(123,3,NULL);
    INSERT INTO t2 VALUES(-10,3,NULL);
    CREATE UNIQUE INDEX t2bc ON t2(b,c);
  

    SELECT a FROM t2 WHERE b=2 AND c IS NULL ORDER BY a;
  


    SELECT a FROM t2 WHERE b=2 AND c IS NULL ORDER BY b, a;
  


    SELECT a FROM t2 WHERE b=2 AND c IS NULL ORDER BY b;
  
