1 {CREATE TABLE t1(x TEXT PRIMARY KEY, y NOT NULL) WITHOUT ROWID
CREATE UNIQUE INDEX t1y ON t1(y)
5 {CREATE TABLE t1(w,x,y NOT NULL,z NOT NULL,PRIMARY KEY(w,x)) WITHOUT ROWID
CREATE UNIQUE INDEX t1yz ON t1(y,z)
CREATE TABLE err1(a,b,c,UNIQUE(rowid));

CREATE TABLE err1(a,b,c,PRIMARY KEY(rowid));

