DROP TABLE IF EXISTS t1;
    CREATE TABLE t1(x int, y int);
    BEGIN;
  
$j
COMMIT;
  
CREATE TABLE t1(x, y) 
DELETE FROM t1 ORDER BY x
DELETE FROM t1 WHERE x=1 ORDER BY x
UPDATE t1 SET y=1 WHERE x=1 ORDER BY x
DELETE FROM t1 AS a WHERE a.x=1
UPDATE t1 AS a SET y=1 WHERE x=1
UPDATE t1 AS a SET y=1 WHERE t1.x=1
DELETE FROM t1 WHERE x=1 OFFSET 2
UPDATE t1 SET y=1 WHERE x=1 OFFSET 2
DROP TABLE t1 
SELECT count(*) FROM t1
DELETE FROM t1
SELECT count(*) FROM t1
DELETE FROM t1 LIMIT 5
SELECT count(*) FROM t1
DELETE FROM t1 ORDER BY x LIMIT 5
SELECT count(*) FROM t1
DELETE FROM t1 RETURNING x, y, '|' ORDER BY x, y LIMIT 5
SELECT count(*) FROM t1
DELETE FROM t1 RETURNING x, y, '|' ORDER BY x  LIMIT 5 OFFSET 2
SELECT count(*) FROM t1
DELETE FROM t1 ORDER BY x LIMIT 5 OFFSET -2
SELECT count(*) FROM t1
DELETE FROM t1 ORDER BY x LIMIT 2, -5
SELECT count(*) FROM t1
DELETE FROM t1 ORDER BY x LIMIT -2, 5
SELECT count(*) FROM t1
DELETE FROM t1 ORDER BY x LIMIT -2, -5
SELECT count(*) FROM t1
DELETE FROM t1 ORDER BY x LIMIT 2, 5
SELECT count(*) FROM t1
DELETE FROM t1 ORDER BY x LIMIT 5 OFFSET 5
SELECT count(*) FROM t1
DELETE FROM t1 ORDER BY x LIMIT 50 OFFSET 30
SELECT count(*) FROM t1
DELETE FROM t1 ORDER BY x LIMIT 30, 50
SELECT count(*) FROM t1
DELETE FROM t1 ORDER BY x LIMIT 50 OFFSET 50
SELECT count(*) FROM t1
SELECT count(*) FROM t1
DELETE FROM t1 WHERE x=1
SELECT count(*) FROM t1
DELETE FROM t1 WHERE x=1 LIMIT 5
SELECT count(*) FROM t1
DELETE FROM t1 WHERE x=1 ORDER BY x LIMIT 5
SELECT count(*) FROM t1
DELETE FROM t1 WHERE x=2 ORDER BY x LIMIT 5 OFFSET 2
SELECT count(*) FROM t1
DELETE FROM t1 WHERE x=2 ORDER BY x LIMIT 5 OFFSET -2
SELECT count(*) FROM t1
DELETE FROM t1 WHERE x=3 ORDER BY x LIMIT 2, -5
SELECT count(*) FROM t1
DELETE FROM t1 WHERE x=3 ORDER BY x LIMIT -2, 5
SELECT count(*) FROM t1
DELETE FROM t1 WHERE x=4 ORDER BY x LIMIT -2, -5
SELECT count(*) FROM t1
DELETE FROM t1 WHERE x=5 ORDER BY x LIMIT 2, 5
SELECT count(*) FROM t1
DELETE FROM t1 WHERE x=6 ORDER BY x LIMIT 5 OFFSET 5
SELECT count(*) FROM t1
DELETE FROM t1 WHERE x=1 ORDER BY x LIMIT 50 OFFSET 30
SELECT count(*) FROM t1
DELETE FROM t1 WHERE x=2 ORDER BY x LIMIT 30, 50
SELECT count(*) FROM t1
DELETE FROM t1 WHERE x=3 ORDER BY x LIMIT 50 OFFSET 50
SELECT count(*) FROM t1
SELECT count(*) FROM t1
UPDATE t1 SET y=1 WHERE x=1
SELECT count(*) FROM t1 WHERE y=1
UPDATE t1 SET y=1 WHERE x=1 RETURNING x, y, '|' LIMIT 5
SELECT count(*) FROM t1 WHERE y=1
UPDATE t1 SET y=2 WHERE x=2 ORDER BY x LIMIT 5
SELECT count(*) FROM t1 WHERE y=2
UPDATE t1 SET y=2 WHERE x=2 ORDER BY x LIMIT 5 OFFSET 2
SELECT count(*) FROM t1 WHERE y=1
UPDATE t1 SET y=2 WHERE x=2 ORDER BY x LIMIT 5 OFFSET -2
SELECT count(*) FROM t1 WHERE y=1
UPDATE t1 SET y=3 WHERE x=3 ORDER BY x LIMIT 2, -5
SELECT count(*) FROM t1 WHERE y=3
UPDATE t1 SET y=3 WHERE x=3 ORDER BY x LIMIT -2, 5
SELECT count(*) FROM t1 WHERE y=3
UPDATE t1 SET y=4 WHERE x=4 ORDER BY x LIMIT -2, -5
SELECT count(*) FROM t1 WHERE y=4
UPDATE t1 SET y=4 WHERE x=5 ORDER BY x LIMIT 2, 5
SELECT count(*) FROM t1 WHERE y=4
UPDATE t1 SET y=4 WHERE x=6 ORDER BY x LIMIT 5 OFFSET 5
SELECT count(*) FROM t1 WHERE y=1
UPDATE t1 SET y=1 WHERE x=1 ORDER BY x LIMIT 50 OFFSET 30
SELECT count(*) FROM t1 WHERE y=1
UPDATE t1 SET y=1 WHERE x=2 ORDER BY x LIMIT 30, 50
SELECT count(*) FROM t1 WHERE y=1
UPDATE t1 SET y=1 WHERE x=3 ORDER BY x LIMIT 50 OFFSET 50
SELECT count(*) FROM t1 WHERE y=1
CREATE TABLE t1(a int);
    INSERT INTO t1 VALUES(1);
    INSERT INTO t1 VALUES(2);
    INSERT INTO t1 VALUES(3);
    CREATE TABLE t2(a int);
    INSERT INTO t2 SELECT a+100 FROM t1;
    CREATE VIEW tv(r,a) AS
       SELECT rowid, a FROM t2 UNION ALL SELECT rowid, a FROM t1;
    CREATE TRIGGER tv_del INSTEAD OF DELETE ON tv
    BEGIN
      DELETE FROM t1 WHERE rowid=old.r;
      DELETE FROM t2 WHERE rowid=old.r;
    END;
  
DELETE FROM tv WHERE 1 LIMIT 2;
  
DELETE FROM tv WHERE 1 ORDER BY a LIMIT 2;
  
CREATE TABLE t3(a,b,c,d TEXT, PRIMARY KEY(a,b)) WITHOUT ROWID;
    INSERT INTO t3(a,b,c,d) VALUES(1,2,3,4),(5,6,7,8),(9,10,11,12);
  
DELETE FROM t3 WHERE a=5 LIMIT 2;
  
SELECT a,b,c,d FROM t3 ORDER BY 1;
  
