
SELECT count(*) FROM t1

DELETE FROM t1
SELECT count(*) FROM t1

DELETE FROM t1 LIMIT 5
SELECT count(*) FROM t1

DELETE FROM t1 ORDER BY x LIMIT 5
SELECT count(*) FROM t1

DELETE FROM t1 RETURNING x, y, '|' ORDER BY x, y LIMIT 5

SELECT count(*) FROM t1

DELETE FROM t1 RETURNING x, y, '|' ORDER BY x  LIMIT 5 OFFSET 2

SELECT count(*) FROM t1

DELETE FROM t1 ORDER BY x LIMIT 5 OFFSET -2
SELECT count(*) FROM t1

DELETE FROM t1 ORDER BY x LIMIT 2, -5
SELECT count(*) FROM t1

DELETE FROM t1 ORDER BY x LIMIT -2, 5
SELECT count(*) FROM t1

DELETE FROM t1 ORDER BY x LIMIT -2, -5
SELECT count(*) FROM t1

DELETE FROM t1 ORDER BY x LIMIT 2, 5
SELECT count(*) FROM t1

DELETE FROM t1 ORDER BY x LIMIT 5 OFFSET 5
SELECT count(*) FROM t1

DELETE FROM t1 ORDER BY x LIMIT 50 OFFSET 30
SELECT count(*) FROM t1

DELETE FROM t1 ORDER BY x LIMIT 30, 50
SELECT count(*) FROM t1

DELETE FROM t1 ORDER BY x LIMIT 50 OFFSET 50
SELECT count(*) FROM t1
