

    CREATE TABLE t1(a PRIMARY KEY, b) WITHOUT rowid;
    CREATE TABLE t2(c INT PRIMARY KEY REFERENCES t1, b) WITHOUT rowid;
  

 INSERT INTO t2 VALUES(1, 'A'); 

 
    INSERT INTO t1 VALUES(1, 2);
    INSERT INTO t1 VALUES(2, 3);
    INSERT INTO t2 VALUES(1, 'A');
  

 UPDATE t2 SET c = 2 

 UPDATE t2 SET c = 3 

 DELETE FROM t1 WHERE a = 2 

 DELETE FROM t1 WHERE a = 1 

 UPDATE t1 SET a = 3 
